const express = require('express')
const router = express.Router()
const passport = require('../../config/passport')
const lessonController = require('../../controllers/pages/lesson-controller')
const adminController = require('../../controllers/pages/admin-controller')
const userController = require('../../controllers/pages/user-controller')
const { generalErrorHandler } = require('../../middleware/error-handler')
const { authenticated, authenticatedAdmin } = require('../../middleware/auth')
router.get('/admin/users', authenticatedAdmin, adminController.getUsers)
router.post('/users/signIn', passport.authenticate('local', { failureRedirect: '/users/signIn', failureFlash: true }), userController.signIn)
router.get('/users/signIn', userController.signInPage)
router.get('/users/signUp', userController.signUpPage)
router.post('/users/signUp', userController.signUp)
router.get('/lessons', lessonController.getLessons)
router.use('/', (req, res) => res.redirect('/lessons'))
router.use('/', generalErrorHandler)

module.exports = router
